name: fcimc
channels:
  - nodefaults
  - conda-forge
dependencies:
  - python=3
  - matplotlib
  - numpy
  - jupyter
  - pip
  - gfortran
  - doxygen
  - graphviz
  - mkdocs
  - mkdocs-material
  - ghp-import
  - pip:
      - git+https://github.com/Feneric/doxypypy
